<script setup>
import {ref,computed} from 'vue'
const api=import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8000';const page=ref('login'),token=ref(localStorage.getItem('token')||''),user=ref(null),modules=ref([]),chosen=ref([]),items=ref([]),error=ref(''),loading=ref(false);const form=ref({username:'',password:'',name:'',role:'student',college:'',major:'',grade:''});const q=ref('');const answer=ref('')
const logged= computed(()=>!!token.value);const title=computed(()=>user.value?.grade==='大一'?'大一新生·入学指南':user.value?.grade==='大四'?'大四学生·就业实习':'为你推荐')
async function req(path,opt={}){opt.headers={...(opt.headers||{}),...(token.value?{Authorization:'Bearer '+token.value}:{})};const r=await fetch(api+path,opt);const d=await r.json();if(!r.ok)throw Error(d.detail||'请求失败');return d}
async function register(){try{await req('/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)});page.value='login';error.value='注册成功，请登录'}catch(e){error.value=e.message}}
async function login(){try{const d=await req('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:form.value.username,password:form.value.password})});token.value=d.access_token;localStorage.setItem('token',token.value);user.value=d.user;const s=await req('/onboarding/status');page.value=s.completed?'home':'onboarding';if(page.value==='onboarding')modules.value=await req('/onboarding/modules');else load()}catch(e){error.value=e.message}}
async function save(){if(chosen.value.length<3)return;await req('/onboarding/interests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module_ids:chosen.value})});user.value.onboarding_completed=true;page.value='home';load()}
async function load(){items.value=(await req('/recommendations')).items}
async function ask(){const d=await req('/rag/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q.value})});answer.value=d.answer}
function logout(){token.value='';user.value=null;localStorage.removeItem('token');page.value='login'}
</script>
<template><main><header><div class="brand"><b>新疆工程学院</b><span>校园信息智能服务平台</span></div><nav v-if="logged"><a @click="page='home'">首页</a><a @click="page='ask'">智能问答</a><a @click="logout">退出</a></nav></header><section class="banner"><h1>{{page==='login'?'欢迎登录':page==='register'?'创建校园账号':page==='onboarding'?'选择你的兴趣模块':title}}</h1><p>让校园信息更懂你</p></section><p class="error">{{error}}</p><section v-if="page==='login'||page==='register'" class="auth"><input v-if="page==='register'" v-model="form.name" placeholder="姓名"><input v-model="form.username" placeholder="用户名"><input v-model="form.password" type="password" placeholder="密码（至少8位）"><template v-if="page==='register'"><select v-model="form.role"><option value="student">学生</option><option value="counselor">辅导员</option><option value="organizer">活动组织者</option></select><input v-model="form.college" placeholder="学院"><input v-model="form.major" placeholder="专业"><select v-if="form.role==='student'" v-model="form.grade"><option value="">选择年级</option><option>大一</option><option>大二</option><option>大三</option><option>大四</option></select></template><button @click="page==='login'?login():register()">{{page==='login'?'登录':'注册'}}</button><a @click="page=page==='login'?'register':'login'">{{page==='login'?'没有账号？立即注册':'已有账号？返回登录'}}</a></section><section v-else-if="page==='onboarding'" class="interest"><p>至少选择 3 个模块，系统会据此生成你的首页推荐。</p><div class="modules"><button v-for="m in modules" :class="{selected:chosen.includes(m.id)}" @click="chosen.includes(m.id)?chosen=chosen.filter(x=>x!==m.id):chosen.push(m.id)">{{m.icon}} {{m.name}}</button></div><button :disabled="chosen.length<3" @click="save">完成选择（{{chosen.length}}）</button></section><section v-else-if="page==='home'" class="feed"><div class="user">{{user?.name}} · {{user?.college}} · {{user?.grade||user?.role}}</div><div class="cards"><article v-for="x in items"><label>{{x.content_type}}</label><h2>{{x.title}}</h2><p>{{x.body}}</p><small>✦ {{x.reason}}</small><button>感兴趣</button></article></div></section><section v-else class="qa"><h2>校园智能问答</h2><input v-model="q" placeholder="例如：大一新生如何报到？"><button @click="ask">提问</button><p>{{answer}}</p></section></main></template>
